f=open('index.html','r')
c=f.read()
f.close()
c=c.replace('updateEntities(dt);','updateEntities(dt);updateAutoLock(dt);updateAutoCombat(dt);',1)
c=c.replace('renderAutoLock();ctx.restore();','renderAutoLock();renderAutoCombat(ctx,camX,camY);ctx.restore();',1)
c=c.replace('if(AXE_IDS.indexOf(h.id)>=0)return 2;return 0;}','if(AXE_IDS.indexOf(h.id)>=0)return 2;if(SWORD_IDS.indexOf(h.id)>=0)return 3;return 0;}',1)
c=c.replace('function updateAutoLock(dt){if(!autoLockEnabled','function updateAutoLock(dt){var tt=getToolType();if(tt===3){autoLockTarget=null;return;}if(!autoLockEnabled',1)
c=c.replace('function updateAutoCombat(dt){if(!autoCombatEnabled','function updateAutoCombat(dt){var tt=getToolType();if(tt!==3){autoCombatTarget=null;}if(!autoCombatEnabled',1)
f=open('index.html','w')
f.write(c)
f.close()
print('All patches applied successfully')